### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/cdp-sdk-sample-apps#25]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/cdp-sdk-sample-apps/compare/c6e39cce878385ba68ce9684f9b460030f754398...c30d3284fb9f5c9483eebc5e9a09d152ab3dfed9) was merged to master by jazz-cb.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/cdp-sdk-sample-apps&ref=b76ed93089799a3f8de080c9727f76afdce4e307)

**Comment by jazz-cb** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for jazz-cb @ 2024-12-11 14:44:07 UTC
User cannot review their own pull request

**Comment by John-peterson-coinbase** [comment]
👍

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/1
------------ | -------------
John-peterson-coinbase | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/cdp-sdk-sample-apps&ref=b76ed93089799a3f8de080c9727f76afdce4e307)
